<a href="https://colab.research.google.com/github/mayurpophale/emotion_pred/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')


## Data gathering

In [2]:
df = pd.read_csv('train.txt', sep=';', header=None,names=['text','emotions'])
df


,text,emotions
0,i didnt feel humiliated,sadness
1,i can go from feeling so hopeless to so damned...,sadness
2,im grabbing a minute to post i feel greedy wrong,anger
3,i am ever feeling nostalgic about the fireplac...,love
4,i am feeling grouchy,anger
...,...,...
15995,i just had a very brief time in the beanbag an...,sadness
15996,i am now turning and i feel pathetic that i am...,sadness
15997,i feel strong and good overall,joy
15998,i feel like this was such a rude comment and i...,anger


In [3]:
df.isnull().sum()

,0
text,0
emotions,0


In [39]:
un_emotions = df['emotions'].unique()
un_emotions

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

## Data cleaning


In [4]:
un_emotions = df['emotions'].unique()
i = 0
emotions_dict = {}
for emotion in un_emotions:
    emotions_dict[emotion] = i
    i += 1
emotions_dict

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

In [5]:
df['emotions'].apply(lambda x: emotions_dict[x])

,emotions
0,0
1,0
2,1
3,2
4,1
...,...
15995,0
15996,0
15997,5
15998,1


In [6]:
df['text'] = df['text'].apply(lambda x: x.lower())
df

,text,emotions
0,i didnt feel humiliated,sadness
1,i can go from feeling so hopeless to so damned...,sadness
2,im grabbing a minute to post i feel greedy wrong,anger
3,i am ever feeling nostalgic about the fireplac...,love
4,i am feeling grouchy,anger
...,...,...
15995,i just had a very brief time in the beanbag an...,sadness
15996,i am now turning and i feel pathetic that i am...,sadness
15997,i feel strong and good overall,joy
15998,i feel like this was such a rude comment and i...,anger


In [7]:
import string

In [8]:
def remove_punctuation(text):
    for punctuation in string.punctuation:
        text = text.replace(punctuation, '')
    return text
df['text']=df['text'].apply(remove_punctuation)

In [9]:
def remove_number(text):
  new = ''
  for i in text:
    if not i.isdigit():
      new += i
  return new
df['text']=df['text'].apply(remove_number)

In [10]:
def remove_emoji(txt):
  new = ''
  for i in txt:
    if i.isascii():
      new +=i
  return new
df['text']=df['text'].apply(remove_emoji)

In [11]:
df.head()

,text,emotions
0,i didnt feel humiliated,sadness
1,i can go from feeling so hopeless to so damned...,sadness
2,im grabbing a minute to post i feel greedy wrong,anger
3,i am ever feeling nostalgic about the fireplac...,love
4,i am feeling grouchy,anger


In [12]:
import nltk
nltk.download

<bound method Downloader.download of <nltk.downloader.Downloader object at 0x7cc9beeda420>>

In [13]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt') #for tokenazatiob

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [14]:
stop_words = set(stopwords.words('english'))

In [15]:
len(stop_words)

198

In [16]:
def remove(txt):
  words = txt.split()
  new_words = []
  for word in words:
    if word not in stop_words:
      new_words.append(word)
  return ' '.join(new_words)
df['text']=df['text'].apply(remove)

# **Bag of words**

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

doct = ['I love pizza',
        'Pizza is the best',
        'I love pastaa',
        'pastaa is great'
        ]
vectorizer  = CountVectorizer(ngram_range=(2,2))
x = vectorizer.fit_transform(doct)

print(vectorizer.get_feature_names_out())
print(x.toarray())

['is great' 'is the' 'love pastaa' 'love pizza' 'pastaa is' 'pizza is'
 'the best']
[[0 0 0 1 0 0 0]
 [0 1 0 0 0 1 1]
 [0 0 1 0 0 0 0]
 [1 0 0 0 1 0 0]]


# **TF-IDF**

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

doct = ['I love pizza',
        'Pizza is the best',
        'I love pastaa',
        'pastaa is great'
        ]
vectorizer  = TfidfVectorizer()
x = vectorizer.fit_transform(doct)

print(vectorizer.get_feature_names_out())
print(x.toarray())

['best' 'great' 'is' 'love' 'pastaa' 'pizza' 'the']
[[0.         0.         0.         0.70710678 0.         0.70710678
  0.        ]
 [0.55528266 0.         0.43779123 0.         0.         0.43779123
  0.55528266]
 [0.         0.         0.         0.70710678 0.70710678 0.
  0.        ]
 [0.         0.66767854 0.52640543 0.         0.52640543 0.
  0.        ]]


continoue of project


In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotions'], test_size=0.2, random_state=42)

In [22]:
X_train

,text
676,refers course though cant help feeling somehow...
12113,im starting feel im suffering fatigue
7077,feel like probably would liked book little bit...
13005,really feel awkward
12123,im feeling little grumpy today lame weather te...
...,...
13418,love leave reader feeling confused slightly de...
5390,feel delicate
860,starting feel little stressed
15795,feel stressed tired worn shape neglected


In [23]:
X_test

,text
8756,ive made week feel beaten
4660,feel strategy worthwhile
6095,feel worthless weak say want find
304,feel clever nov
8241,im moved ive feeling kind gloomy
...,...
15578,feel useful pulpit find ironic often question ...
5746,dried bladders ready day im feeling brave
6395,feel thrilled matter days
7624,woke morning text mr c declaring walking work ...


In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

bow_vect = CountVectorizer()
X_train_bow = bow_vect.fit_transform(X_train)
X_test_bow = bow_vect.transform(X_test)

In [29]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)
y_pred = nb_model.predict(X_test_bow)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.768125


In [34]:
#tf-idf with nayve basyes
tf_idf_vect = TfidfVectorizer()
X_train_tf_idf = tf_idf_vect.fit_transform(X_train)
X_test_tf_idf = tf_idf_vect.transform(X_test)
nb2_model = MultinomialNB()


In [35]:
nb2_model.fit(X_train_tf_idf, y_train)
y_pred = nb2_model.predict(X_test_tf_idf)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.6609375


In [36]:
#now tfidf with logistic regression
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression()
lr_model.fit(X_train_tf_idf, y_train)
y_pred = lr_model.predict(X_test_tf_idf)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8628125


In [37]:
import joblib
joblib.dump(lr_model, 'lr_model.pkl')

['lr_model.pkl']

In [41]:
joblib.dump(tf_idf_vect, 'tfidf.pkl')

['tfidf.pkl']